ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only:[:index, :show, :new, :create, :edit, :update]
  resources :cat_rental_requests, only:[:new]
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
require "action_view"
require "action_view/helpers"

COLORS = ['White', 'Black', 'Ginger', 'Cream', 'Cinnamon']

class Cat < ApplicationRecord

    include ActionView::Helpers

    validates :birth_date, presence: true
    validates :color, presence: true, inclusion: {in: COLORS,
        message: "%{value} is not a valid color" }
    validates :name, presence: true
    validates :sex, presence: true, inclusion: {in: ['M', 'F'],
        message: "invalid" }
    validates :description, presence: true

    def age
        time_ago_in_words(birth_date)
    end

    has_many :rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy


end

ninety_nine_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord 
    validates :cat_id, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :status, inclusion: {in: ['APPROVED', 'DENIED', 'PENDING']}
    validate :does_not_overlap_approved_request
    belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat


    def overlapping_requests
       CatRentalRequest.where(cat_id: cat_id, start_date: (start_date..end_date)).where.not(id: id)
                        .or(CatRentalRequest.where(cat_id: cat_id, end_date: (start_date..end_date)).where.not(id: id))
    end

    def overlapping_approved_requests
        overlapping_requests.where(status: 'APPROVED')
    end

    def does_not_overlap_approved_request
        if overlapping_approved_requests.exists?
            errors[:overlapping] << 'approved request exists'
        end 
    end


end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def new 
        @cats = Cat.all
        @request = CatRentalRequest.new
        render :new
    end

    def create 
        @request = CatRentalRequest.new(request_params)
        if @request.save 
            render plain: 'request submitted'
        else 
            render :new 
        end 
    end

    # def show 
    #     @request =
    # end 

end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end 

    def show 
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    private

    def cat_params
        params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
    end
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cat_rental_requests/new.html.erb
<h1> Book A Cat! </h1>
<form action="<%= cat_rental_requests_url %>" method="post">
 <label for="cats">Select your Playmate!</label>
  <select id="cats" name="request[cat_id]">
    <option disabled >-- Please Select --</option>
        <% @cats.each do |cat| %> 
    <option value="<%= cat.id  %>"><%= cat.name %></option>
    <% end %>
  </select>

    <br>

   <label for="start_date">Select your start date</label>
  <input id="start_date" type="date" name="request[start_date]" value="">

    <br>

   <label for="end_date">Select your end date</label>
  <input id="end_date" type="date" name="request[end_date]" value="">
    
    <br>
    
   <input type="submit" value= 'Submit your request ;)'>
</form>

ninety_nine_cats/app/views/cats/_form.html.erb
<% if edit  %>
    <% action_url = cat_url(cat) %>
<% else %>
    <% action_url = cats_url %>
<% end %>
<form action="<%= action_url %>" method="post">
<% if edit  %>
    <input type="hidden" name="_method" value="PATCH">
<% end %>
  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>

  <p>Sex:</p>
  <br>
  <input id="male" type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? "checked" : "" %>>
  <label for="male">Male</label>
  <input id="female" type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? "checked" : "" %>>
  <label for="female">Female</label>

  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled >-- Please Select --</option>
        <% COLORS.each do |color| %> 
    <option value="<%= color  %>"<%= cat.color == color ? "selected" : "" %>><%= color  %></option>
    <% end %>
  </select>

  <br>

  <label for="birth_date">Birth date</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br><br>

  <label for="description">Description</label>
  <textarea name="cat[description]"><%= cat.description %></textarea>

  <input type="submit" value= '<%= edit ? 'update cat' : 'add cat'%>'>
</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<h1>Tweak your cat!</h1>
<%= render 'form', cat: @cat, edit: true %>

ninety_nine_cats/app/views/cats/index.html.erb
<h1> All of the Cats in the WORLD!! </h1>

<section> 
    <section> 
    <ul>
    <% @cats.each do |cat| %> 
    <li>rent <a href='<%= cat_url(cat) %>'> <%= cat.name %> </a> </li>
    <% end %>
    </ul>
    </section>

 </section>

ninety_nine_cats/app/views/cats/new.html.erb
<h1>Put your cat on the market!</h1>
<%= render 'form', cat: @cat, edit: false %>

ninety_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %>
<p>
    <%= @cat.description %>
</p>
<table> 
    <thead>
        <tr>
            <th>Attribute</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td>AGE</td>
            <td><%= @cat.age %></td>
        </tr>
        <tr>
            <td>BIRTH_DATE</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>COLOR</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>SEX</td>
            <td><%= @cat.sex %></td>
        </tr>
    </tbody>
</table>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>